name: CI
on:
  workflow_dispatch:

env:
  VK_VERSION: 1.3.261.1
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "{{ VK_VERSION }}"
        key: "vulkansdk-linux-x86_64-{{ VK_VERSION }}"
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/vulkansdk-linux-x86_64-$VK_VERSION.tar.xz?Human=true -O vulkansdk-linux-x86_64-$VK_VERSION.tar.xz
        tar -xf vulkansdk-linux-x86_64-$VK_VERSION.tar.xz
        rm -rf $VK_VERSION/source $VK_VERSION/samples
        find $VK_VERSION -type f | grep -v -E 'vulkan|glslang' | xargs rm
    - name: build
      run: |
        export VULKAN_SDK=`pwd`/$VK_VERSION/x86_64
        mkdir build && cd build
        cmake ../src
        cmake --build . -j 2
